export enum CabinetActions {
  UPDATE = "UPDATE_CABINET",
  CREATE = "CREATE_CABINET",
  MOVE_LEFT = "MOVE_LEFT_CABINET",
  MOVE_RIGHT = "MOVE_RIGHT_CABINET",
  DELETE = "DELETE_CABINET"
}

export enum SectionActions {
  UPDATE = "UPDATE_SECTION",
  CREATE = "CREATE_SECTION",
  MOVE_UP = "MOVE_SECTION_UP",
  MOVE_DOWN = "MOVE_SECTION_DOWN ",
  DELETE = "DELETE_SECTION"
}

export enum BookActions {
  UPDATE = "UPDATE_BOOK",
  CREATE = "CREATE_BOOK",
  MOVE_LEFT = "MOVE_LEFT_BOOK",
  MOVE_RIGHT = "MOVE_RIGH_BOOKT",
  COPY = "COPY_BOOK",
  CUT = "CUT_BOOK",
  PASTE = "PASTE_BOOK",
  DELETE = "DELETE_BOOK"
}
